package az.edu.turing.dao.entity;

public enum Cities {
    LONDON, PARIS, NEW_YORK, TOKYO, DUBAI, ISTANBUL, SINGAPORE, KUALA_LUMPUR, SEOUL, HONG_KONG, BAKU, BANGKOK,
    LOS_ANGELES, BARCELONA, ROME, MILAN, MADRID, BERLIN, MUNICH, FRANKFURT, AMSTERDAM, VIENNA, ZURICH, GENEVA,
    BRUSSELS, COPENHAGEN, STOCKHOLM, OSLO, HELSINKI, WARSAW, PRAGUE, BUDAPEST, ATHENS, LISBON, MOSCOW, SAINT_PETERSBURG,
    KIEV, MINSK, RIGA, TALLINN, VILNIUS, SOFIA, BUCHAREST, BELGRADE, ZAGREB, SARAJEVO, SKOPJE, TIRANA, PRISTINA, PODGORICA,
    CHISINAU, TBILISI, YEREVAN, ASTANA, ALMATY, TASHKENT, ASHGABAT, BISHKEK, DUSHANBE, KHUJAND, ANKARA, TEHRAN, BAGHDAD,
    DAMASCUS, BEIRUT, JERUSALEM, AMMAN, CAIRO, TRIPOLI, TUNIS, ALGIERS, RABAT, CASABLANCA, DAKAR, BAMAKO, OUAGADOUGOU,
    NIAMEY, KHARTOUM, ADDIS_ABABA, NAIROBI, DAR_ES_SALAAM, KAMPALA, KIGALI, BUJUMBURA, DODOMA, LUSAKA, HARARE, GABORONE,
    MAPUTO, WINDHOEK, PRETORIA, CAPE_TOWN, BLOEMFONTEIN, JOHANNESBURG, DURBAN, PORT_ELIZABETH, EAST_LONDON, MBABANE, MASERU,
    VICTORIA, PORT_LOUIS, SAINT_DENIS, SAINT_PIERRE, SAINT_BARTHELEMY, SAINT_MARTIN, SAINT_LUCIA, SAINT_VINCENT, SAINT_KITTS,
    SAINT_JOHN, SAINT_THOMAS, SAINT_CROIX, SAINT_MAARTEN, SAINT_EUSTATIUS, SAINT_BARTELEMY, SAINT, SAINT_HELENA, SAINT_PETER;

    public static Cities getCity(String name) {
        try {
            for (Cities city : values()) {
                if (city.name().equalsIgnoreCase(name.toUpperCase())) {
                    return city;
                }
            }
        } catch (IllegalArgumentException e) {
            System.err.println("Invalid city name: " + name);
        }
        return null;
    }


}
